swagger: "2.0"
info:
  description: "This is a server for a course project"
  version: "1.0.0"
  title: "Dalilah Resto"
  contact:
    email: "snreynoso@gmail.com"
tags:
- name: "admin"
  description: "Operations as Administrator"
- name: "user"
  description: "Operations about user"
paths:
  /user/order:
    get:
      summary: "User order resume" 
      description: "Resume of the menus added to the order by the user"
      responses:
        200:
          description: OK
    
  /user/register:
    post:
      tags:
      - "user"
      summary: "Create user"
      description: "Create a new user profile"
      operationId: "register"
      parameters:
      - in: "body"
        name: "body"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/definitions/UserRegister"
      responses:
        "200":
          description: "Successful registry operation"
        "400":
          description: "Invalid username supplied"
        "404":
          description: "Fail to create new user"
  
definitions:
  UserRegister:
    type: "object"
    properties:
      userName:
        type: "string"
      name:
        type: "string"
      email:
        type: "string"
      phone:
        type: "string"
      adress: 
        type: "string"
      password:
        type: "string"
    xml:
      name: "UserRegister"
  Admin:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      username:
        type: "string"
      firstName:
        type: "string"
      lastName:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
      phone:
        type: "string"
      userStatus:
        type: "integer"
        format: "int32"
        description: "Admin Status"
    xml:
      name: "Admin"
      